export const SET_INITIAL_YEAR = "SET_INITIAL_YEAR";
export const SET_FINISH_YEAR = "SET_FINISH_YEAR";
export const GET_COMMODITIES = "GET_COMMODITIES";
export const COMMODITIES_ERROR = "COMMODITIES_ERROR";
